## **Data Science Bootcamp, Spring '25**

<br>

---

### Assignment 2 : **Numpy and Pandas**
#### Student: **Samrudhi Baldota**
#### NetID: **sb10212**

---
---

###  **Numpy**

In [2]:
import numpy as np

# Load the dataset
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# 1. Define two custom numpy arrays A and B, and stack them vertically and horizontally.
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])

vertical_stack = np.vstack((A, B))
horizontal_stack = np.hstack((A, B))

print("Vertical Stack:\n", vertical_stack)
print("Horizontal Stack:\n", horizontal_stack)



Vertical Stack:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Horizontal Stack:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [3]:
# 2. Find common elements between A and B.
common_elements = np.intersect1d(A, B)
print("Common Elements:", common_elements)



Common Elements: []


In [4]:
# 3. Extract all numbers from A which are within a specific range (5 to 10).
filtered_A = A[(A >= 5) & (A <= 10)]
print("Numbers in A between 5 and 10:", filtered_A)




Numbers in A between 5 and 10: [5 6]


In [5]:
# 4. Filter rows of iris_2d where petal length (3rd column) > 1.5 and sepal length (1st column) < 5.0
filtered_iris = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print("Filtered iris_2d:\n", filtered_iris)

Filtered iris_2d:
 [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


### **Pandas**

In [6]:
import pandas as pd
import numpy as np

# 1. Filter 'Manufacturer', 'Model', and 'Type' for every 20th row starting from 1st row
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
filtered_rows = df.loc[::20, ['Manufacturer', 'Model', 'Type']]
print(filtered_rows)




   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [7]:
# 2. Replace missing values in Min.Price and Max.Price columns with their respective mean.
df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
df['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)
print(df[['Min.Price', 'Max.Price']].isnull().sum())  # Check if missing values are replaced



Min.Price    0
Max.Price    0
dtype: int64


<ipython-input-7-b1dfeb19efae>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
<ipython-input-7-b1dfeb19efae>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)'

In [8]:
# 3. Get rows where the row sum is greater than 100
df_random = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
rows_with_sum_gt_100 = df_random[df_random.sum(axis=1) > 100]
print("Rows with sum > 100:\n", rows_with_sum_gt_100)

Rows with sum > 100:
      0   1   2   3
1   20  23  37  35
2   17  34  27  34
5   14  35  21  32
9   38  11  23  32
11  18  39  35  11
13  31  30  18  39
14  29  23  18  38
